# Generated by Django 3.2.13 on 2022-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('total_applied', models.IntegerField(default=0)),
                ('publishedDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
